### ISSUE TITLE
progress bars

### ISSUE THREAD

**Issue by MohitKS5** [kanthvallampati/IVORY#10]
can i add progress bars to your repository?

**Comment by kanthvallampati** [comment]
Sure, But I would like to review the code first. Can you send me the code to my mail kanth.vallampati@gmail.com

**Comment by MohitKS5** [comment]
Sure give me a day or two ...to match ur indentation and comment style

**Comment by kanthvallampati** [comment]
The indentation and comment style what you see In the current ivory.css is not the one I follow. I have used some wrong plugin and the indentation became like this. I will update the indentation and comments in a day or two. So you can follow the updated style.

**Comment by MohitKS5** [comment]
I sent the pull request. You can check that it works perfectly with your package as I included progress bars after ALERTS in index.html.
